### ISSUE TITLE
Are there any plans to make interface customisable?

### ISSUE THREAD

**Issue by artem-shmatkov** [kinescope/ios-kinescope-player#2]

**Comment by NullIsOne** [comment]
You can use `KinescopePlayerView.setLayout` to configure components of player view, but `KinescopeFullscreenViewController` will still use default layout configuration. It's our fault.

We planed to add full customisation but didn't implement it, because we found that some of the UI components are difficult to implement and it's better for users if they will be included into SDK.

If you have customise an interface in your fork repository, you're welcome to open PR. We will glad to see your vision of best player.

**Comment by NullIsOne** [comment]
Good news for you.
We have improved player UI customisation in latest release https://github.com/kinescope/ios-kinescope-player/releases/tag/0.2 
There is still old method `KinescopePlayerView.setLayout` but now you can combine different configurations easier using builders.

Also, in master you can find updated `Documentation.md` with illustrations of subviews which can help you to understand which configuration you need customise.
